### ISSUE TITLE
For jupyter-labhub add a link to an associated nbviewer instance in the menu

### ISSUE THREAD

**Issue by rcthomas** [krinsman/clonenotebooks#4]
Consider whether there is a way for jupyter-labhub to figure out whether there is an associated nbviewer service being run through the hub and if so, create a link to it in perhaps the File dropdown menu so a user can just click that and go to nbviewer directly.

**Comment by krinsman** [comment]
@rcthomas I'm a little confused -- do you want this resolved and https://github.com/krinsman/clonenotebooks/issues/5 ?

So for this one, what you want is an extra menu item that says "NBViewer" or something like that?

<img width="233" alt="Captura de Pantalla 2019-09-18 a la(s) 10 43 40 a  m" src="https://user-images.githubusercontent.com/31422259/65172087-3b867200-da01-11e9-9007-cb90fcd6ebe1.png">

But if it was also possible to open NBViewer as an IFrame in a new JupyterLab tab, wouldn't that make adding a menu option to run the hub service directly redundant? (I.e. https://github.com/krinsman/clonenotebooks/issues/5)

Or in that case do you just have in mind (for this issue) something like a new entry in the Command Palette?

<img width="230" alt="Captura de Pantalla 2019-09-18 a la(s) 10 46 03 a  m" src="https://user-images.githubusercontent.com/31422259/65172346-9029ed00-da01-11e9-8ff5-566e83b0c9d7.png">

**Comment by rcthomas** [comment]
... maybe let's close this one for now.  To keep it simple, perhaps the thing to focus on is "can there be a way to include links to services that have URLs from the Hub UI?"

The problem here is that Lab would need to know nbviewer is running, and it can find that out from the hub, but there's not an agreed-upon mechanism for detecting running services on a hub from JupyterLab.  The idea of just putting a link in the Hub for now is a half measure but would be a useful thing to solve.
